package netactuate

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/netactuate/gona/gona"
)

type ProviderClients struct {
	V2 *gona.Client
	V3 *gona.V3Client
}

func Provider() *schema.Provider {
	p := &schema.Provider{
		Schema: map[string]*schema.Schema{
			"api_key": {
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				DefaultFunc: schema.EnvDefaultFunc("NETACTUATE_API_KEY", nil),
			},
			"api_url": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"api_url_v3": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Base URL for the vAPI3 endpoint. Defaults to https://vapi3.netactuate.com",
			},
		},
		ResourcesMap: map[string]*schema.Resource{
			"netactuate_server":                              resourceServer(),
			"netactuate_sshkey":                              resourceSshKey(),
			"netactuate_bgp_group":                           resourceBGPGroup(),
			"netactuate_bgp_group_firewall_set":              resourceBGPGroupFirewallSet(),
			"netactuate_bgp_prefix_purchase":                 resourceBGPPrefixPurchase(),
			"netactuate_bgp_sessions":                        resourceBGPSessions(),
			"netactuate_dedicated_server_buy":                resourceDedicatedServerBuy(),
			"netactuate_dedicated_server_deployment":         resourceDedicatedServerDeployment(),
			"netactuate_dedicated_server_buy_build":          resourceDedicatedServerBuyBuild(),
			"netactuate_dedicated_server_ipv4_reverse":       resourceDedicatedServerIPv4Reverse(),
			"netactuate_dedicated_server_power_status":       resourceDedicatedServerPowerStatus(),
			"netactuate_metal":                               resourceMetal(),
			"netactuate_vpc":                                 resourceVPC(),
			"netactuate_vpc_gateway_dnat_rule":               resourceVPCGatewayDNATRule(),
			"netactuate_vpc_gateway_snat_rule":               resourceVPCGatewaySNATRule(),
			"netactuate_vpc_gateway_firewall_rule":           resourceVPCGatewayFirewallRule(),
			"netactuate_vpc_gateway_standby":                 resourceVPCStandbyGateway(),
			"netactuate_vpc_nameservers":                     resourceVPCNameservers(),
			"netactuate_vpc_floating_ip":                     resourceVPCFloatingIP(),
			"netactuate_vpc_ssh_key":                         resourceVPCSSHKey(),
			"netactuate_vpc_backend_template":                resourceVPCBackendTemplate(),
			"netactuate_vpc_backend_template_backends":       resourceVPCBackendTemplateBackends(),
			"netactuate_network_loadbalancer_group":          resourceNetworkLoadbalancerGroup(),
			"netactuate_ssl_certificate":                     resourceSSLCertificate(),
			"netactuate_http_loadbalancer_group":             resourceHTTPLoadbalancerGroup(),
			"netactuate_nke_cluster":                         resourceNKECluster(),
			"netactuate_nke_access_urls":                     resourceNKEAccessURLs(),
			"netactuate_nke_worker_node":                     resourceNKEWorkerNode(),
			"netactuate_nke_dns_addon":                       resourceNKEDNSAddon(),
			"netactuate_nke_storage_addon":                   resourceNKEStorageAddon(),
			"netactuate_storage_bucket":                      resourceStorageBucket(),
			"netactuate_storage_object_store":                resourceStorageObjectStore(),
			"netactuate_storage_block_namespace":             resourceStorageBlockNamespace(),
			"netactuate_storage_block_volume":                resourceStorageBlockVolume(),
			"netactuate_secret_list":                         resourceSecretList(),
			"netactuate_secret_list_value":                   resourceSecretListValue(),
			"netactuate_router":                              resourceRouter(),
			"netactuate_router_ntp":                          resourceRouterNTP(),
			"netactuate_router_vrf":                          resourceRouterVRF(),
			"netactuate_router_vrf_dhcp":                     resourceRouterVRFDHCP(),
			"netactuate_router_vrf_interface":                resourceRouterVRFInterface(),
			"netactuate_router_vrf_interface_wireguard_peer": resourceRouterVRFInterfaceWireguardPeer(),
			"netactuate_router_vrf_bgp":                      resourceRouterVRFBGP(),
			"netactuate_router_vrf_bgp_neighbor":             resourceRouterVRFBGPNeighbor(),
			"netactuate_router_vrf_snat_rule":                resourceRouterVRFSNATRule(),
			"netactuate_router_vrf_dnat_rule":                resourceRouterVRFDNATRule(),
			"netactuate_router_vrf_tunnel":                   resourceRouterVRFTunnel(),
			"netactuate_router_static_route":                 resourceRouterStaticRoute(),
			"netactuate_router_prefix_list":                  resourceRouterPrefixList(),
			"netactuate_router_ipsec":                        resourceRouterIPSec(),
			"netactuate_router_vrf_ipsec_peer":               resourceRouterVRFIPSecPeer(),
			"netactuate_router_routing_view":                 resourceRouterRoutingView(),
			"netactuate_magic_mesh":                          resourceMagicMesh(),
			"netactuate_magic_mesh_router":                   resourceMagicMeshRouter(),
			"netactuate_firewall_set":                        resourceFirewallSet(),
			"netactuate_firewall_rule":                       resourceFirewallRule(),
			"netactuate_firewall_set_vm":                     resourceFirewallSetVM(),
			"netactuate_firewall_set_vm_detach":              resourceFirewallSetVMDetach(),
			"netactuate_firewall_set_rule_order":             resourceFirewallSetRuleOrder(),
			"netactuate_firewall_set_detach_all_vms":         resourceFirewallSetDetachAllVMs(),
			"netactuate_server_nic":                          resourceServerNIC(),
			"netactuate_oidc_client":                         resourceOIDCClient(),
			"netactuate_oidc_client_key":                     resourceOIDCClientKey(),
			"netactuate_oidc_client_vm_allow_list":           resourceOIDCClientVMAllowList(),
			"netactuate_oidc_client_bare_metal_allow_list":   resourceOIDCClientBareMetalAllowList(),
			"netactuate_image":                               resourceImage(),
			"netactuate_dns_zone":                            resourceDNSZone(),
			"netactuate_dns_record":                          resourceDNSRecord(),
			"netactuate_access_control_subnet":               resourceAccessControlSubnet(),
			"netactuate_tag":                                 resourceTag(),
			"netactuate_tag_assignment":                      resourceTagAssignment(),
			"netactuate_usage_contract":                      resourceUsageContract(),
			"netactuate_cloud_ipv4_reverse_dns":              resourceCloudIPv4ReverseDNS(),
			"netactuate_cloud_ipv6_reverse_dns":              resourceCloudIPv6ReverseDNS(),
			"netactuate_cloud_floating_ipv4":                 resourceCloudFloatingIPv4(),
			"netactuate_cloud_floating_ipv4_vm_grant":        resourceCloudFloatingIPv4VMGrant(),
			"netactuate_server_options":                      resourceServerOptions(),
			"netactuate_cloud_firewall_set_binding":          resourceCloudFirewallSetBinding(),
		},
		DataSourcesMap: map[string]*schema.Resource{
			"netactuate_server":                                 dataSourceServer(),
			"netactuate_servers":                                dataSourceServers(),
			"netactuate_sshkey":                                 dataSourceSshKey(),
			"netactuate_sshkeys":                                dataSourceSshKeys(),
			"netactuate_bgp_groups":                             dataSourceBGPGroups(),
			"netactuate_bgp_asn":                                dataSourceBGPASN(),
			"netactuate_bgp_prefixes":                           dataSourceBGPPrefixes(),
			"netactuate_bgp_prefix":                             dataSourceBGPPrefix(),
			"netactuate_bgp_asns":                               dataSourceBGPASNs(),
			"netactuate_bgp_summary":                            dataSourceBGPSummary(),
			"netactuate_bgp_dashboard":                          dataSourceBGPDashboard(),
			"netactuate_bgp_sessions":                           dataSourceBGPSessions(),
			"netactuate_account_agreements":                     dataSourceAccountAgreements(),
			"netactuate_nke_versions":                           dataSourceNKEVersions(),
			"netactuate_nke_addons":                             dataSourceNKEAddons(),
			"netactuate_nke_dns_zones":                          dataSourceNKEDNSZones(),
			"netactuate_nke_worker_nodes":                       dataSourceNKEWorkerNodes(),
			"netactuate_nke_kubeconfig":                         dataSourceNKEKubeconfig(),
			"netactuate_cloud_routing_meshes":                   dataSourceCloudRoutingMeshes(),
			"netactuate_cloud_routing_routers":                  dataSourceCloudRoutingRouters(),
			"netactuate_cloud_routing_router_interfaces":        dataSourceCloudRoutingRouterInterfaces(),
			"netactuate_cloud_routing_router_vrfs":              dataSourceCloudRoutingRouterVRFs(),
			"netactuate_cloud_routing_router_vrf_bgp_neighbors": dataSourceCloudRoutingRouterVRFBGPNeighbors(),
			"netactuate_cloud_routing_router_vrf_interfaces":    dataSourceCloudRoutingRouterVRFInterfaces(),
			"netactuate_cloud_routing_router_vrf_tunnels":       dataSourceCloudRoutingRouterVRFTunnels(),
			"netactuate_cloud_routing_router_routing_overview":  dataSourceCloudRoutingRouterRoutingOverview(),
			"netactuate_locations":                              dataSourceLocations(),
			"netactuate_plans":                                  dataSourcePlans(),
			"netactuate_sizes":                                  dataSourceSizes(),
			"netactuate_vlans":                                  dataSourceVLANs(),
			"netactuate_cloud_floating_ips":                     dataSourceCloudFloatingIPs(),
			"netactuate_server_nics":                            dataSourceServerNICs(),
			"netactuate_account_limits":                         dataSourceAccountLimits(),
			"netactuate_packages":                               dataSourcePackages(),
			"netactuate_billing_packages":                       dataSourceBillingPackages(),
			"netactuate_colocation_packages":                    dataSourceColocationPackages(),
			"netactuate_colocation_package":                     dataSourceColocationPackage(),
			"netactuate_transit_packages":                       dataSourceTransitPackages(),
			"netactuate_transit_package":                        dataSourceTransitPackage(),
			"netactuate_location":                               dataSourceLocationByCurrentIP(),
			"netactuate_cloud_pools":                            dataSourceCloudPools(),
			"netactuate_cloud_capacity":                         dataSourceCloudCapacity(),
			"netactuate_dedicated_capacity":                     dataSourceDedicatedCapacity(),
			"netactuate_dedicated_devices":                      dataSourceDedicatedDevices(),
			"netactuate_dedicated_locations":                    dataSourceDedicatedLocations(),
			"netactuate_dedicated_device_os_profiles":           dataSourceDedicatedDeviceOSProfiles(),
			"netactuate_dedicated_plans":                        dataSourceDedicatedPlans(),
			"netactuate_dedicated_servers":                      dataSourceDedicatedServers(),
			"netactuate_os_images":                              dataSourceOSImages(),
			"netactuate_tags":                                   dataSourceTags(),
			"netactuate_boot_profiles":                          dataSourceBootProfiles(),
			"netactuate_server_disks":                           dataSourceServerDisks(),
			"netactuate_dedicated_os_profiles":                  dataSourceDedicatedOSProfiles(),
			"netactuate_dedicated_rescue_os":                    dataSourceDedicatedRescueOS(),
			"netactuate_dedicated_disk_layouts":                 dataSourceDedicatedDiskLayouts(),
			"netactuate_storage_locations":                      dataSourceStorageLocations(),
			"netactuate_storage_types":                          dataSourceStorageTypes(),
			"netactuate_storage_block_namespaces":               dataSourceStorageBlockNamespaces(),
			"netactuate_storage_buckets":                        dataSourceStorageBuckets(),
			"netactuate_storage_object_stores":                  dataSourceStorageObjectStores(),
			"netactuate_image":                                  dataSourceImage(),
			"netactuate_my_images":                              dataSourceMyImages(),
			"netactuate_secret_lists":                           dataSourceSecretLists(),
			"netactuate_secret_list_values":                     dataSourceSecretListValues(),
			"netactuate_secret_values":                          dataSourceSecretValues(),
			"netactuate_dns_zone":                               dataSourceDNSZone(),
			"netactuate_vpc_floating_ips":                       dataSourceVPCFloatingIPs(),
			"netactuate_vpcs":                                   dataSourceVPCs(),
			"netactuate_vpc_locations":                          dataSourceVPCLocations(),
			"netactuate_vpc_gateway_firewall_rules":             dataSourceVPCGatewayFirewallRules(),
			"netactuate_vpc_gateway_dnat_rules":                 dataSourceVPCGatewayDNATRules(),
			"netactuate_vpc_gateway_snat_rules":                 dataSourceVPCGatewaySNATRules(),
			"netactuate_vpc_backend_templates":                  dataSourceVPCBackendTemplates(),
			"netactuate_vpc_ip_reservations":                    dataSourceVPCIPReservations(),
			"netactuate_vpc_ssh":                                dataSourceVPCSSHSettings(),
			"netactuate_firewall_sets":                          dataSourceFirewallSets(),
			"netactuate_firewall_rules":                         dataSourceFirewallRules(),
			"netactuate_firewall_set_vms":                       dataSourceFirewallSetVMs(),
			"netactuate_firewall_external_ipsets":               dataSourceFirewallExternalIPSets(),
			"netactuate_firewall_manage_enabled":                dataSourceFirewallManageEnabled(),
			"netactuate_firewall_set_related_vms":               dataSourceFirewallSetRelatedVMs(),
			"netactuate_firewall_set_available_vms":             dataSourceFirewallSetAvailableVMs(),
			"netactuate_server_ips":                             dataSourceServerIPs(),
			"netactuate_storage_block_volumes":                  dataSourceStorageBlockVolumes(),
			"netactuate_resource_tags":                          dataSourceResourceTags(),
			"netactuate_contract_usage":                         dataSourceContractUsage(),
			"netactuate_metric_names":                           dataSourceMetricNames(),
			"netactuate_statistics":                             dataSourceStatistics(),
			"netactuate_networking_statistics":                  dataSourceNetworkingStatistics(),
			"netactuate_anycast_statistics":                     dataSourceAnycastStatistics(),
			"netactuate_platform_status":                        dataSourcePlatformStatus(),
			"netactuate_platform_change_log":                    dataSourcePlatformChangeLog(),
			"netactuate_platform_change_log_entry":              dataSourcePlatformChangeLogEntry(),
			"netactuate_platform_datacenters":                   dataSourcePlatformDatacenters(),
			"netactuate_platform_looking_glass_init":            dataSourcePlatformLookingGlassInit(),
			"netactuate_platform_looking_glass":                 dataSourcePlatformLookingGlass(),
			"netactuate_platform_maintenance_info":              dataSourcePlatformMaintenanceInfo(),
			"netactuate_platform_incidents":                     dataSourcePlatformIncidents(),
			"netactuate_platform_incident_history":              dataSourcePlatformIncidentHistory(),
			"netactuate_platform_maintenance":                   dataSourcePlatformMaintenance(),
			"netactuate_platform_maintenance_history":           dataSourcePlatformMaintenanceHistory(),
			"netactuate_ddos_attacks":                           dataSourceDDoSAttacks(),
			"netactuate_ddos_active_attacks":                    dataSourceDDoSActiveAttacks(),
			"netactuate_ddos_dashboard":                         dataSourceDDoSDashboard(),
			"netactuate_ddos_rules":                             dataSourceDDoSRules(),
			"netactuate_ddos_rule":                              dataSourceDDoSRule(),
			"netactuate_http_loadbalancer_groups":               dataSourceHTTPLoadbalancerGroups(),
			"netactuate_ssl_certificates":                       dataSourceSSLCertificates(),
			"netactuate_services":                               dataSourceServices(),
			"netactuate_colocation_services":                    dataSourceColocationServices(),
			"netactuate_colocation_service":                     dataSourceColocationService(),
			"netactuate_iptransit_services":                     dataSourceIPTransitServices(),
			"netactuate_iptransit_service":                      dataSourceIPTransitService(),
			"netactuate_iptransit_ips":                          dataSourceIPTransitIPs(),
			"netactuate_iptransit_ports":                        dataSourceIPTransitPorts(),
			"netactuate_transport_services":                     dataSourceTransportServices(),
			"netactuate_transport_service":                      dataSourceTransportService(),
			"netactuate_transport_ports":                        dataSourceTransportPorts(),
			"netactuate_oidc_clients":                           dataSourceOIDCClients(),
			"netactuate_oidc_client":                            dataSourceOIDCClient(),
			"netactuate_oidc_client_keys":                       dataSourceOIDCClientKeys(),
			"netactuate_oidc_client_bare_metal_servers":         dataSourceOIDCClientBareMetalServers(),
			"netactuate_oidc_client_auth_logs":                  dataSourceOIDCClientAuthLogs(),
			"netactuate_oidc_client_change_logs":                dataSourceOIDCClientChangeLogs(),
			"netactuate_tag_resources":                          dataSourceTagResources(),
			"netactuate_tag_logs":                               dataSourceTagLogs(),
			"netactuate_access_control_subnets":                 dataSourceAccessControlSubnets(),
			"netactuate_access_control_subnet":                  dataSourceAccessControlSubnet(),
			"netactuate_cloud_extras":                           dataSourceCloudExtras(),
			"netactuate_images_provisioning_jobs_count":         dataSourceImagesProvisioningJobsCount(),
			"netactuate_cloud_base_images":                      dataSourceCloudBaseImages(),
			"netactuate_cloud_private_images":                   dataSourceCloudPrivateImages(),
			"netactuate_cloud_iplimits":                         dataSourceCloudIPLimits(),
			"netactuate_cloud_kernels":                          dataSourceCloudKernels(),
			"netactuate_cloud_location":                         dataSourceCloudLocation(),
			"netactuate_cloud_floating_ipv4_vms":                dataSourceCloudFloatingIPv4VMs(),
			"netactuate_cloud_networking_locations":             dataSourceCloudNetworkingLocations(),
			"netactuate_cloud_location_vlans":                   dataSourceCloudLocationVLANs(),
			"netactuate_cloud_vlan":                             dataSourceCloudVLAN(),
			"netactuate_cloud_pool":                             dataSourceCloudPool(),
			"netactuate_cloud_scaling_options":                  dataSourceCloudScalingOptions(),
			"netactuate_server_deployment_info":                 dataSourceServerDeploymentInfo(),
			"netactuate_server_vnc_status":                      dataSourceServerVNCStatus(),
			"netactuate_server_ipv4":                            dataSourceServerIPv4(),
			"netactuate_server_ipv6":                            dataSourceServerIPv6(),
			"netactuate_server_networkips":                      dataSourceServerNetworkIPs(),
			"netactuate_server_bgp_sessions_raw":                dataSourceServerBGPSessionsRaw(),
			"netactuate_current_server":                         dataSourceCurrentServer(),
			"netactuate_unprovisioned_packages":                 dataSourceUnprovisionedPackages(),
			"netactuate_virtual_server_contract":                dataSourceVirtualServerContract(),
			"netactuate_server_summary":                         dataSourceServerSummary(),
			"netactuate_cloud_plan_id":                          dataSourceCloudPlanID(),
			"netactuate_cloud_deploy_sizes":                     dataSourceCloudDeploySizes(),
			"netactuate_cloud_storage_locations":                dataSourceCloudStorageLocations(),
		},
		ConfigureContextFunc: providerConfigure,
	}
	applyDocumentation(p)
	return p
}

func providerConfigure(ctx context.Context, d *schema.ResourceData) (interface{}, diag.Diagnostics) {
	var diags diag.Diagnostics

	apiKey := d.Get("api_key").(string)
	apiUrl := d.Get("api_url").(string)
	apiUrlV3 := d.Get("api_url_v3").(string)

	if apiKey == "" {
		diags = append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  "Unable to create NetActuate API client",
			Detail: `Unable to find NetActuate API key. It can be set with either NETACTUATE_API_KEY environment
variable or 'api_key' property`,
		})
		return nil, diags
	}

	var v2Client *gona.Client
	if apiUrl == "" {
		v2Client = gona.NewClient(apiKey)
	} else {
		v2Client = gona.NewClientCustom(apiKey, apiUrl)
	}

	v3Client := gona.NewV3Client(apiKey, apiUrlV3)

	if locations, err := v2Client.GetLocations(); err == nil {
		setCachedLocationCatalog(locations)
	} else {
		setCachedLocationCatalog(nil)
	}

	return &ProviderClients{
		V2: v2Client,
		V3: v3Client,
	}, nil
}
