package netactuate

import (
	"context"
	"strconv"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/netactuate/gona/gona"
)

func resourceRouterVRFInterfaceWireguardPeer() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceRouterVRFInterfaceWireguardPeerCreate,
		ReadContext:   resourceRouterVRFInterfaceWireguardPeerRead,
		DeleteContext: resourceRouterVRFInterfaceWireguardPeerDelete,
		Schema: map[string]*schema.Schema{
			"router_id": {
				Type:        schema.TypeInt,
				Required:    true,
				ForceNew:    true,
				Description: "The ID of the cloud router.",
			},
			"vrf_id": {
				Type:        schema.TypeInt,
				Required:    true,
				ForceNew:    true,
				Description: "The ID of the VRF.",
			},
			"interface_id": {
				Type:        schema.TypeInt,
				Required:    true,
				ForceNew:    true,
				Description: "The ID of the wireguard interface.",
			},
			"name": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "The name of the wireguard interface.",
			},
			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "The description of the wireguard interface.",
			},
			"remote": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "The remote address of the wireguard interface.",
				RequiredWith: []string{"public_key"},
			},
			"wireguard_peer_id": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "The ID of the wireguard peer.",
			},
			"allowed_ips": {
				Type:        schema.TypeList,
				Required:    true,
				ForceNew:    true,
				Description: "The list of IP networks allowed to traverse the tunnel.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"network": {
							Type:        schema.TypeString,
							Required:    true,
							ForceNew:    true,
							Description: "An individual allowed network in CIDR notation.",
						},
					},
				},
			},
			"public_key": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Sensitive:   true,
				Computed:    true,
				Description: "The base64 public key for the wireguard peer. If not provided, a key pair will be generated.",
			},
			"private_key": {
				Type:        schema.TypeString,
				Computed:    true,
				Sensitive:   true,
				Description: "The base64 private key for the wireguard peer (only available if generated by the system).",
			},
			"pre_shared_key": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Sensitive:   true,
				Description: "An optional pre-shared key for additional security.",
			},
		},
	}
}

func resourceRouterVRFInterfaceWireguardPeerCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*ProviderClients).V3

	routerID := d.Get("router_id").(int)
	vrfID := d.Get("vrf_id").(int)
	interfaceID := d.Get("interface_id").(int)

	unlock := lockRouter(routerID)
	defer unlock()

	allowedIPsList := d.Get("allowed_ips").([]interface{})
	allowedIPs := make([]gona.WireguardPeerAllowedIP, len(allowedIPsList))
	for i, item := range allowedIPsList {
		ipMap := item.(map[string]interface{})
		allowedIPs[i] = gona.WireguardPeerAllowedIP{
			Network: ipMap["network"].(string),
		}
	}

	createRequest := gona.CreateRouterVRFInterfaceWireguardPeerRequest{
		AllowedIPs: allowedIPs,
	}

	if v, ok := d.GetOk("public_key"); ok {
		publicKey := v.(string)
		createRequest.PublicKey = &publicKey
	}

	if v, ok := d.GetOk("pre_shared_key"); ok {
		preSharedKey := v.(string)
		createRequest.PreSharedKey = &preSharedKey
	}

	if v, ok := d.GetOk("name"); ok {
		name := v.(string)
		createRequest.Name = &name
	}

	if v, ok := d.GetOk("description"); ok {
		description := v.(string)
		createRequest.Description = &description
	}

	if v, ok := d.GetOk("remote"); ok {
		remote := v.(string)
		createRequest.Remote = &remote
	}

	createResp, err := c.CreateRouterVRFInterfaceWireguardPeer(routerID, vrfID, interfaceID, createRequest)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(strconv.Itoa(createResp.WireguardPeerID))

	return resourceRouterVRFInterfaceWireguardPeerRead(ctx, d, m)
}

func resourceRouterVRFInterfaceWireguardPeerRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*ProviderClients).V3

	routerID := d.Get("router_id").(int)
	vrfID := d.Get("vrf_id").(int)
	interfaceID := d.Get("interface_id").(int)
	wireguardPeerID, err := strconv.Atoi(d.Id())
	if err != nil {
		return diag.FromErr(err)
	}

	peer, err := c.GetRouterVRFInterfaceWireguardPeer(routerID, vrfID, interfaceID, wireguardPeerID)
	if err != nil {
		if gona.IsV3NotFound(err) {
			d.SetId("")
			return nil
		}
		return diag.FromErr(err)
	}

	var diags diag.Diagnostics

	setValue("router_id", routerID, d, &diags)
	setValue("vrf_id", vrfID, d, &diags)
	setValue("interface_id", interfaceID, d, &diags)
	setValue("wireguard_peer_id", peer.WireguardPeerID, d, &diags)
	setValue("public_key", peer.PublicKey, d, &diags)
	setValue("private_key", peer.PrivateKey, d, &diags)
	setValue("name", peer.Name, d, &diags)
	setValue("description", peer.Description, d, &diags)
	setValue("remote", peer.Remote, d, &diags)

	allowedIPs := make([]map[string]interface{}, len(peer.AllowedIPs))
	for i, ip := range peer.AllowedIPs {
		allowedIPs[i] = map[string]interface{}{
			"network": ip.Network,
		}
	}
	setValue("allowed_ips", allowedIPs, d, &diags)

	if peer.PreSharedKey != nil {
		setValue("pre_shared_key", peer.PreSharedKey, d, &diags)
	}

	return diags
}

func resourceRouterVRFInterfaceWireguardPeerDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*ProviderClients).V3

	routerID := d.Get("router_id").(int)
	vrfID := d.Get("vrf_id").(int)
	interfaceID := d.Get("interface_id").(int)

	unlock := lockRouter(routerID)
	defer unlock()

	wireguardPeerID, err := strconv.Atoi(d.Id())
	if err != nil {
		return diag.FromErr(err)
	}

	err = c.DeleteRouterVRFInterfaceWireguardPeer(routerID, vrfID, interfaceID, wireguardPeerID)
	if err != nil {
		if gona.IsV3NotFound(err) {
			return nil
		}
		return diag.FromErr(err)
	}
	return nil
}